In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df= pd.read_excel(r"C:\Users\LENOVO\Downloads\technocolabs\H-1B_Disclosure_Data_FY2019.xlsx")
print(df)

               CASE_NUMBER CASE_STATUS      CASE_SUBMITTED  \
0       I-200-16092-327771   WITHDRAWN 2016-04-08 00:00:00
1       I-203-17188-450729   WITHDRAWN 2017-07-14 00:00:00
2       I-203-17229-572307   WITHDRAWN 2017-08-23 00:00:00
3       I-203-17356-299648   WITHDRAWN 2017-12-22 00:00:00
4       I-203-18008-577576   WITHDRAWN 2018-01-10 00:00:00
...                    ...         ...                 ...
664611  I-200-18282-647333   CERTIFIED 2018-10-09 18:10:32
664612  I-200-19046-203745      DENIED 2019-02-15 16:53:11
664613  I-200-19059-900658      DENIED 2019-02-28 01:11:11
664614  I-200-19063-784427      DENIED 2019-03-04 08:37:04
664615  I-200-19073-908844      DENIED 2019-03-14 08:14:46

             DECISION_DATE ORIGINAL_CERT_DATE      VISA_CLASS  \
0      2019-04-30 00:00:00                NaT            H-1B
1      2019-05-13 00:00:00                NaT  E-3 Australian
2      2019-04-30 00:00:00                NaT  E-3 Australian
3      2019-08-20 00:00:00                NaT  E-3 Australian
4      2019-04-15 00:00:00                NaT  E-3 Australian
...                    ...                ...             ...
664611 2018-10-15 22:00:43                NaT            H-1B
664612 2019-02-22 10:45:38                NaT            H-1B
664613 2019-03-07 16:07:41                NaT            H-1B
664614 2019-03-08 12:01:58                NaT            H-1B
664615 2019-03-19 11:41:04                NaT            H-1B

                          JOB_TITLE                      SOC_CODE  \
0       ASSOCIATE CREATIVE DIRECTOR                       11-2011
1       ACCOUNT SUPERVISOR (MOTHER)                       11-2011
2       EXECUTIVE CREATIVE DIRECTOR                       11-2011
3           PROJECT MANAGEMENT LEAD                       11-2011
4             CREATIVE DIRECTOR, UX                       11-2011
...                             ...                           ...
664611  DIGITAL TOUCHPOINTS ANALYST  OPERATIONS RESEARCH ANALYSTS
664612    APPLICATIONS CONSULTANT 2                           NaN
664613   BUSINESS SYSTEMS ANALYST 2                           NaN
664614    APPLICATIONS CONSULTANT 2                           NaN
664615   BUSINESS SYSTEMS ANALYST 2                           NaN

                                  SOC_TITLE FULL_TIME_POSITION  ...  \
0       ADVERTISING AND PROMOTIONS MANAGERS                  Y  ...
1       ADVERTISING AND PROMOTIONS MANAGERS                  Y  ...
2       ADVERTISING AND PROMOTIONS MANAGERS                  Y  ...
3       ADVERTISING AND PROMOTIONS MANAGERS                  Y  ...
4       ADVERTISING AND PROMOTIONS MANAGERS                  Y  ...
...                                     ...                ...  ...
664611                              15-2031                  Y  ...
664612                                  NaN                  Y  ...
664613                                  NaN                  Y  ...
664614                                  NaN                  Y  ...
664615                                  NaN                  Y  ...

       PW_OTHER_SOURCE_10 PW_NON-OES_YEAR_10  PW_SURVEY_PUBLISHER_10  \
0                     NaN                NaN                     NaN
1                     NaN                NaN                     NaN
2                     NaN                NaN                     NaN
3                     NaN                NaN                     NaN
4                     NaN                NaN                     NaN
...                   ...                ...                     ...
664611                NaN                NaN                     NaN
664612                NaN                NaN                     NaN
664613                NaN                NaN                     NaN
664614                NaN                NaN                     NaN
664615                NaN                NaN                     NaN

       PW_SURVEY_NAME_10 H-1B_DEPENDENT  WILLFUL_VIOLATOR  SUPPORT_H1B  \
0                    NaN              N                 N          NaN
1                    NaN            NaN               NaN          NaN
2                    NaN            NaN               NaN          NaN
3                    NaN            NaN               NaN          NaN
4                    NaN            NaN               NaN          NaN
...                  ...            ...               ...          ...
664611               NaN              N                 N          NaN
664612               NaN              Y                 N            Y
664613               NaN              Y                 N            Y
664614               NaN              Y                 N            Y
664615               NaN              Y                 N            Y

        STATUTORY_BASIS  MASTERS_EXEMPTION  PUBLIC_DISCLOSURE
0                   NaN                NaN                NaN
1                   NaN                NaN                NaN
2                   NaN                NaN                NaN
3                   NaN                NaN                NaN
4                   NaN                NaN                NaN
...                 ...                ...                ...
664611              NaN                NaN  PLACE OF BUSINESS
664612             WAGE                NaN  PLACE OF BUSINESS
664613             WAGE                NaN  PLACE OF BUSINESS
664614             WAGE                NaN  PLACE OF BUSINESS
664615             WAGE                NaN  PLACE OF BUSINESS

[664616 rows x 260 columns]

In [4]:
df.head(1000)

,CASE_NUMBER,CASE_STATUS,CASE_SUBMITTED,DECISION_DATE,ORIGINAL_CERT_DATE,VISA_CLASS,JOB_TITLE,SOC_CODE,SOC_TITLE,FULL_TIME_POSITION,...,PW_OTHER_SOURCE_10,PW_NON-OES_YEAR_10,PW_SURVEY_PUBLISHER_10,PW_SURVEY_NAME_10,H-1B_DEPENDENT,WILLFUL_VIOLATOR,SUPPORT_H1B,STATUTORY_BASIS,MASTERS_EXEMPTION,PUBLIC_DISCLOSURE
0,I-200-16092-327771,WITHDRAWN,2016-04-08 00:00:00,2019-04-30 00:00:00,NaT,H-1B,ASSOCIATE CREATIVE DIRECTOR,11-2011,ADVERTISING AND PROMOTIONS MANAGERS,Y,...,NaN,NaN,NaN,NaN,N,N,NaN,NaN,NaN,NaN
1,I-203-17188-450729,WITHDRAWN,2017-07-14 00:00:00,2019-05-13 00:00:00,NaT,E-3 Australian,ACCOUNT SUPERVISOR (MOTHER),11-2011,ADVERTISING AND PROMOTIONS MANAGERS,Y,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I-203-17229-572307,WITHDRAWN,2017-08-23 00:00:00,2019-04-30 00:00:00,NaT,E-3 Australian,EXECUTIVE CREATIVE DIRECTOR,11-2011,ADVERTISING AND PROMOTIONS MANAGERS,Y,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,I-203-17356-299648,WITHDRAWN,2017-12-22 00:00:00,2019-08-20 00:00:00,NaT,E-3 Australian,PROJECT MANAGEMENT LEAD,11-2011,ADVERTISING AND PROMOTIONS MANAGERS,Y,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,I-203-18008-577576,WITHDRAWN,2018-01-10 00:00:00,2019-04-15 00:00:00,NaT,E-3 Australian,"CREATIVE DIRECTOR, UX",11-2011,ADVERTISING AND PROMOTIONS MANAGERS,Y,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,I-203-18349-689310,CERTIFIED,2018-12-15 19:34:24,2018-12-20 22:01:13,NaT,E-3 Australian,ASSOCIATE PROJECT DIRECTOR,11-2021,MARKETING MANAGERS,Y,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PLACE OF BUSINESS
996,I-200-18347-298510,CERTIFIED,2018-12-17 09:25:21,2018-12-21 22:00:12,NaT,H-1B,PRINCIPAL PRODUCT MANAGER - PAYMENT PRODUCTS NA,11-2021,MARKETING MANAGERS,Y,...,NaN,NaN,NaN,NaN,N,N,NaN,NaN,NaN,PLACE OF BUSINESS
997,I-200-18351-912428,CERTIFIED,2018-12-17 10:17:49,2018-12-21 22:00:14,NaT,H-1B,RUG PRODUCT LINE MARKETING AND MERCHANDISING M...,11-2021,MARKETING MANAGERS,Y,...,NaN,NaN,NaN,NaN,N,N,NaN,NaN,NaN,PLACE OF EMPLOYMENT
998,I-200-18346-560119,CERTIFIED,2018-12-17 10:26:04,2018-12-21 22:00:15,NaT,H-1B,BUSINESS DEVELOPMENT DIRECTOR,11-2021,MARKETING MANAGERS,Y,...,NaN,NaN,NaN,NaN,N,N,NaN,NaN,NaN,PLACE OF BUSINESS
999,I-203-18341-115055,CERTIFIED,2018-12-17 10:58:36,2018-12-21 22:00:18,NaT,E-3 Australian,SENIOR MARKETING MANAGER,11-2021,MARKETING MANAGERS,Y,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PLACE OF BUSINESS

In [5]:
df.shape

(664616, 260)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 664616 entries, 0 to 664615
Columns: 260 entries, CASE_NUMBER to PUBLIC_DISCLOSURE
dtypes: datetime64[ns](3), float64(81), int64(3), object(173)
memory usage: 1.3+ GB

In [9]:
df.describe()

,TOTAL_WORKER_POSITIONS,CHANGE_PREVIOUS_EMPLOYMENT,NEW_CONCURRENT_EMPLOYMENT,CHANGE_EMPLOYER,AMENDED_PETITION,NAICS_CODE,WORKSITE_WORKERS_1,WAGE_RATE_OF_PAY_FROM_1,WAGE_RATE_OF_PAY_TO_1,PREVAILING_WAGE_1,...,PW_NON-OES_YEAR_9,PW_SURVEY_PUBLISHER_9,WORKSITE_WORKERS_10,WORKSITE_POSTAL_CODE_10,WAGE_RATE_OF_PAY_FROM_10,WAGE_RATE_OF_PAY_TO_10,PREVAILING_WAGE_10,PW_OES_YEAR_10,PW_NON-OES_YEAR_10,PW_SURVEY_PUBLISHER_10
count,664614.000000,664616.000000,664615.000000,664616.000000,664616.000000,664614.000000,580900.000000,6.646080e+05,3.328550e+05,631369.000000,...,303.000000,93.000000,288.000000,288.000000,288.000000,120.000000,288.000000,79.000000,206.000000,79.000000
mean,1.604953,0.121800,0.013208,0.254923,0.223296,450965.588053,5.118612,9.383640e+04,1.077588e+05,84331.625656,...,2018.412541,2018.161290,3.378472,47751.086806,121666.356007,124975.303417,87865.179583,2018.253165,2018.407767,2018.253165
std,4.422125,0.907174,0.283244,1.109193,0.896687,190115.692575,489.230557,4.708376e+04,5.378552e+04,35950.599109,...,0.550233,0.726671,5.718649,29978.676785,103333.352227,122285.307455,64047.134457,0.518092,0.548824,0.518092
min,1.000000,0.000000,0.000000,0.000000,0.000000,31.000000,1.000000,7.500000e+00,0.000000e+00,7.250000,...,2018.000000,2013.000000,1.000000,2115.000000,11.200000,11.200000,9.530000,2017.000000,2018.000000,2017.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000,454111.000000,1.000000,7.311200e+04,8.100000e+04,68578.000000,...,2018.000000,2018.000000,1.000000,18510.000000,58067.190000,77.025000,55640.000000,2018.000000,2018.000000,2018.000000
50%,1.000000,0.000000,0.000000,0.000000,0.000000,541511.000000,1.000000,9.000000e+04,1.000000e+05,84240.000000,...,2018.000000,2018.000000,1.000000,44011.000000,89718.050000,89416.550000,65159.000000,2018.000000,2018.000000,2018.000000
75%,1.000000,0.000000,0.000000,0.000000,0.000000,541512.000000,1.000000,1.136720e+05,1.300000e+05,102648.000000,...,2019.000000,2018.000000,1.000000,77786.000000,205500.000000,210000.000000,120161.500000,2019.000000,2019.000000,2019.000000
max,594.000000,338.000000,99.000000,99.000000,99.000000,928120.000000,160500.000000,3.300000e+06,3.000000e+06,849680.000000,...,2020.000000,2019.000000,45.000000,99218.000000,525000.000000,500000.000000,282235.000000,2019.000000,2020.000000,2019.000000

In [7]:
data = df[['CASE_STATUS','VISA_CLASS', 'EMPLOYER_NAME','AGENT_REPRESENTING_EMPLOYER',
           'JOB_TITLE','SOC_TITLE','SOC_CODE','NAICS_CODE','CONTINUED_EMPLOYMENT','CHANGE_PREVIOUS_EMPLOYMENT',
           'NEW_CONCURRENT_EMPLOYMENT','CHANGE_EMPLOYER','AMENDED_PETITION','H-1B_DEPENDENT','SUPPORT_H1B'
          ,'WILLFUL_VIOLATOR','WAGE_RATE_OF_PAY_FROM_1','WAGE_UNIT_OF_PAY_1',
          'TOTAL_WORKER_POSITIONS']]
data

,CASE_STATUS,VISA_CLASS,EMPLOYER_NAME,AGENT_REPRESENTING_EMPLOYER,JOB_TITLE,SOC_TITLE,SOC_CODE,NAICS_CODE,CONTINUED_EMPLOYMENT,CHANGE_PREVIOUS_EMPLOYMENT,NEW_CONCURRENT_EMPLOYMENT,CHANGE_EMPLOYER,AMENDED_PETITION,H-1B_DEPENDENT,SUPPORT_H1B,WILLFUL_VIOLATOR,WAGE_RATE_OF_PAY_FROM_1,WAGE_UNIT_OF_PAY_1,TOTAL_WORKER_POSITIONS
0,WITHDRAWN,H-1B,"R/GA MEDIA GROUP, INC.",NaN,ASSOCIATE CREATIVE DIRECTOR,ADVERTISING AND PROMOTIONS MANAGERS,11-2011,541810.0,1,0,0.0,0,0,N,NaN,N,179000.0,Year,1.0
1,WITHDRAWN,E-3 Australian,MOTHER INDUSTRIES LLC,NaN,ACCOUNT SUPERVISOR (MOTHER),ADVERTISING AND PROMOTIONS MANAGERS,11-2011,541810.0,1,0,0.0,0,0,NaN,NaN,NaN,110000.0,Year,1.0
2,WITHDRAWN,E-3 Australian,"WE ARE UNLIMITED, INC.",NaN,EXECUTIVE CREATIVE DIRECTOR,ADVERTISING AND PROMOTIONS MANAGERS,11-2011,541810.0,0,1,0.0,0,0,NaN,NaN,NaN,275000.0,Year,1.0
3,WITHDRAWN,E-3 Australian,"HELLO ELEPHANT, LLC",NaN,PROJECT MANAGEMENT LEAD,ADVERTISING AND PROMOTIONS MANAGERS,11-2011,541810.0,0,1,0.0,0,0,NaN,NaN,NaN,140000.0,Year,1.0
4,WITHDRAWN,E-3 Australian,"HELLO ELEPHANT, LLC",NaN,"CREATIVE DIRECTOR, UX",ADVERTISING AND PROMOTIONS MANAGERS,11-2011,541810.0,0,1,0.0,0,0,NaN,NaN,NaN,180000.0,Year,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664611,CERTIFIED,H-1B,AMERICAN FAMILY MUTUAL INSURANCE COMPANY,Y,DIGITAL TOUCHPOINTS ANALYST,15-2031,OPERATIONS RESEARCH ANALYSTS,524113.0,0,0,0.0,1,0,N,NaN,N,85500.0,Year,1.0
664612,DENIED,H-1B,CAPGEMINI AMERICA INC,N,APPLICATIONS CONSULTANT 2,NaN,NaN,5416.0,0,0,0.0,0,0,Y,Y,N,80800.0,Year,1.0
664613,DENIED,H-1B,CAPGEMINI AMERICA INC,N,BUSINESS SYSTEMS ANALYST 2,NaN,NaN,5416.0,0,0,0.0,0,0,Y,Y,N,74500.0,Year,1.0
664614,DENIED,H-1B,CAPGEMINI AMERICA INC,N,APPLICATIONS CONSULTANT 2,NaN,NaN,5416.0,0,0,0.0,0,0,Y,Y,N,75900.0,Year,1.0
664615,DENIED,H-1B,CAPGEMINI AMERICA INC,NaN,BUSINESS SYSTEMS ANALYST 2,NaN,NaN,5416.0,1,0,0.0,0,0,Y,Y,N,66700.0,Year,1.0

In [10]:
data.dtypes

CASE_STATUS                     object
VISA_CLASS                      object
EMPLOYER_NAME                   object
AGENT_REPRESENTING_EMPLOYER     object
JOB_TITLE                       object
SOC_TITLE                       object
SOC_CODE                        object
NAICS_CODE                     float64
CONTINUED_EMPLOYMENT            object
CHANGE_PREVIOUS_EMPLOYMENT       int64
NEW_CONCURRENT_EMPLOYMENT      float64
CHANGE_EMPLOYER                  int64
AMENDED_PETITION                 int64
H-1B_DEPENDENT                  object
SUPPORT_H1B                     object
WILLFUL_VIOLATOR                object
WAGE_RATE_OF_PAY_FROM_1        float64
WAGE_UNIT_OF_PAY_1              object
TOTAL_WORKER_POSITIONS         float64
dtype: object

In [11]:
data.isnull().sum()

CASE_STATUS                         0
VISA_CLASS                          0
EMPLOYER_NAME                      10
AGENT_REPRESENTING_EMPLOYER     28150
JOB_TITLE                           1
SOC_TITLE                           4
SOC_CODE                            4
NAICS_CODE                          2
CONTINUED_EMPLOYMENT                0
CHANGE_PREVIOUS_EMPLOYMENT          0
NEW_CONCURRENT_EMPLOYMENT           1
CHANGE_EMPLOYER                     0
AMENDED_PETITION                    0
H-1B_DEPENDENT                  15074
SUPPORT_H1B                    426317
WILLFUL_VIOLATOR                15079
WAGE_RATE_OF_PAY_FROM_1             8
WAGE_UNIT_OF_PAY_1                  8
TOTAL_WORKER_POSITIONS              2
dtype: int64

In [12]:
data= data.dropna(subset=['EMPLOYER_NAME','JOB_TITLE','SOC_TITLE','SOC_CODE','NAICS_CODE',
                          'NEW_CONCURRENT_EMPLOYMENT','WAGE_RATE_OF_PAY_FROM_1','WAGE_UNIT_OF_PAY_1',
                          'TOTAL_WORKER_POSITIONS'])

In [13]:
data.isnull().sum()

CASE_STATUS                         0
VISA_CLASS                          0
EMPLOYER_NAME                       0
AGENT_REPRESENTING_EMPLOYER     28145
JOB_TITLE                           0
SOC_TITLE                           0
SOC_CODE                            0
NAICS_CODE                          0
CONTINUED_EMPLOYMENT                0
CHANGE_PREVIOUS_EMPLOYMENT          0
NEW_CONCURRENT_EMPLOYMENT           0
CHANGE_EMPLOYER                     0
AMENDED_PETITION                    0
H-1B_DEPENDENT                  15073
SUPPORT_H1B                    426302
WILLFUL_VIOLATOR                15078
WAGE_RATE_OF_PAY_FROM_1             0
WAGE_UNIT_OF_PAY_1                  0
TOTAL_WORKER_POSITIONS              0
dtype: int64

In [14]:
mode=data['AGENT_REPRESENTING_EMPLOYER'].mode()
mode1=data['H-1B_DEPENDENT'].mode()
mode2=data['WILLFUL_VIOLATOR'].mode()
mode
mode1
mode2

0    N
dtype: object

In [15]:
data['AGENT_REPRESENTING_EMPLOYER'].fillna(value=mode,inplace=True)
data['H-1B_DEPENDENT'].fillna(value=mode1, inplace=True)
data['WILLFUL_VIOLATOR'].fillna(value=mode2,inplace=True)

c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pandas\core\generic.py:6383: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [17]:
data.isnull().sum()

CASE_STATUS                         0
VISA_CLASS                          0
EMPLOYER_NAME                       0
AGENT_REPRESENTING_EMPLOYER     28144
JOB_TITLE                           0
SOC_TITLE                           0
SOC_CODE                            0
NAICS_CODE                          0
CONTINUED_EMPLOYMENT                0
CHANGE_PREVIOUS_EMPLOYMENT          0
NEW_CONCURRENT_EMPLOYMENT           0
CHANGE_EMPLOYER                     0
AMENDED_PETITION                    0
H-1B_DEPENDENT                  15073
SUPPORT_H1B                    426302
WILLFUL_VIOLATOR                15078
WAGE_RATE_OF_PAY_FROM_1             0
WAGE_UNIT_OF_PAY_1                  0
TOTAL_WORKER_POSITIONS              0
dtype: int64

In [16]:
data.drop_duplicates()

,CASE_STATUS,VISA_CLASS,EMPLOYER_NAME,AGENT_REPRESENTING_EMPLOYER,JOB_TITLE,SOC_TITLE,SOC_CODE,NAICS_CODE,CONTINUED_EMPLOYMENT,CHANGE_PREVIOUS_EMPLOYMENT,NEW_CONCURRENT_EMPLOYMENT,CHANGE_EMPLOYER,AMENDED_PETITION,H-1B_DEPENDENT,SUPPORT_H1B,WILLFUL_VIOLATOR,WAGE_RATE_OF_PAY_FROM_1,WAGE_UNIT_OF_PAY_1,TOTAL_WORKER_POSITIONS
0,WITHDRAWN,H-1B,"R/GA MEDIA GROUP, INC.",Y,ASSOCIATE CREATIVE DIRECTOR,ADVERTISING AND PROMOTIONS MANAGERS,11-2011,541810.0,1,0,0.0,0,0,N,NaN,N,179000.0,Year,1.0
1,WITHDRAWN,E-3 Australian,MOTHER INDUSTRIES LLC,NaN,ACCOUNT SUPERVISOR (MOTHER),ADVERTISING AND PROMOTIONS MANAGERS,11-2011,541810.0,1,0,0.0,0,0,NaN,NaN,NaN,110000.0,Year,1.0
2,WITHDRAWN,E-3 Australian,"WE ARE UNLIMITED, INC.",NaN,EXECUTIVE CREATIVE DIRECTOR,ADVERTISING AND PROMOTIONS MANAGERS,11-2011,541810.0,0,1,0.0,0,0,NaN,NaN,NaN,275000.0,Year,1.0
3,WITHDRAWN,E-3 Australian,"HELLO ELEPHANT, LLC",NaN,PROJECT MANAGEMENT LEAD,ADVERTISING AND PROMOTIONS MANAGERS,11-2011,541810.0,0,1,0.0,0,0,NaN,NaN,NaN,140000.0,Year,1.0
4,WITHDRAWN,E-3 Australian,"HELLO ELEPHANT, LLC",NaN,"CREATIVE DIRECTOR, UX",ADVERTISING AND PROMOTIONS MANAGERS,11-2011,541810.0,0,1,0.0,0,0,NaN,NaN,NaN,180000.0,Year,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664607,CERTIFIED,H-1B,AMSPEC LLC,Y,PETROLEUM INSPECTOR,TRANSPORTATION INSPECTORS,53-6051,541380.0,1,0,0.0,0,0,N,NaN,N,56992.0,Year,1.0
664608,CERTIFIED,H-1B,"INTERTEK USA, INC",Y,INSPECTOR V,TRANSPORTATION INSPECTORS,53-6051,541380.0,1,0,0.0,0,0,N,NaN,N,76377.6,Year,1.0
664609,DENIED,H-1B,"PORT LOGISTICS TERMINAL OPERATIONS, LLC",N,CONTAINER MOBILE HARBOR CRANE OPERATOR,CRANE AND TOWER OPERATORS,53-7021,488320.0,0,0,0.0,0,0,N,NaN,N,32.0,Hour,6.0
664610,CERTIFIED,H-1B,"PORT LOGISTICS TERMINAL OPERATIONS, LLC",N,CONTAINER MOBILE HARBOR CRANE OPERATOR,CRANE AND TOWER OPERATORS,53-7021,488320.0,0,0,0.0,0,0,N,NaN,N,32.0,Hour,6.0
664611,CERTIFIED,H-1B,AMERICAN FAMILY MUTUAL INSURANCE COMPANY,Y,DIGITAL TOUCHPOINTS ANALYST,15-2031,OPERATIONS RESEARCH ANALYSTS,524113.0,0,0,0.0,1,0,N,NaN,N,85500.0,Year,1.0